### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by rekpero** [priyansuhub/spheron-sdk-ts#1]
Most directory conventions are based on kebab-case like - `deployment-environment.`
It would be better if you could follow the kebab case convention when creating files and directories.
For e.g
```
src
---deployment-environment
------index.ts
------types.ts
```

Since you are already named the directory based on the feature, I think you don't need to create the file with the same name. Using `index.ts` will make the imports cleaner, and you can put all the types inside the `types.ts` file without requiring to name it specific to the feature.

Let me know what you think of this. We would like to see more maintainable code that can be adopted as an official library for interacting with Spheron API.

**Comment by priyansuhub** [comment]
Changed folder structure by following the kebab case
removed extra files and kept only index.ts and types.ts in every file
